set -gx theme_display_git yes
set -gx theme_display_git_untracked no
set -gx theme_display_git_ahead_verbose yes
set -gx theme_git_worktree_support yes
set -gx theme_display_vagrant yes
set -gx theme_display_docker_machine no
set -gx theme_display_hg no
set -gx theme_display_virtualenv yes
set -gx theme_display_ruby no
set -gx theme_display_user yes
set -gx theme_display_vi no
set -gx theme_display_date no
set -gx theme_display_cmd_duration yes
set -gx theme_title_display_process yes
set -gx theme_title_display_user yes
set -gx theme_title_display_path no
set -gx theme_title_use_abbreviated_path no
set -gx theme_date_format "+%a %H:%M"
set -gx theme_avoid_ambiguous_glyphs yes
set -gx theme_powerline_fonts yes
set -gx theme_nerd_fonts no
set -gx theme_show_exit_status yes
set -xg default_user leoyzen
set -gx theme_color_scheme zenburn
set -gx fish_prompt_pwd_dir_length 1
set -gx theme_project_dir_length 1
